// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3qb9cTLfVm68mr1SPDgdczmKA6dNUXUk',
    appId: '1:597011689764:web:00706cba3fa0f13df6c3b1',
    messagingSenderId: '597011689764',
    projectId: 'safeguard-ai-123',
    authDomain: 'safeguard-ai-123.firebaseapp.com',
    storageBucket: 'safeguard-ai-123.firebasestorage.app',
    measurementId: 'G-MN437Y3FFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAccP7hUzXMneMzObXUMBiEVdo4RQ6IZMU',
    appId: '1:597011689764:android:5d2b66318ea749dbf6c3b1',
    messagingSenderId: '597011689764',
    projectId: 'safeguard-ai-123',
    storageBucket: 'safeguard-ai-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KLT8QUsAgyM5aS4SoIH9Pjx25frNRDY',
    appId: '1:597011689764:ios:9a2cdcf62893d3bbf6c3b1',
    messagingSenderId: '597011689764',
    projectId: 'safeguard-ai-123',
    storageBucket: 'safeguard-ai-123.firebasestorage.app',
    iosBundleId: 'com.example.safeguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6KLT8QUsAgyM5aS4SoIH9Pjx25frNRDY',
    appId: '1:597011689764:ios:9a2cdcf62893d3bbf6c3b1',
    messagingSenderId: '597011689764',
    projectId: 'safeguard-ai-123',
    storageBucket: 'safeguard-ai-123.firebasestorage.app',
    iosBundleId: 'com.example.safeguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3qb9cTLfVm68mr1SPDgdczmKA6dNUXUk',
    appId: '1:597011689764:web:e4579bd014673f26f6c3b1',
    messagingSenderId: '597011689764',
    projectId: 'safeguard-ai-123',
    authDomain: 'safeguard-ai-123.firebaseapp.com',
    storageBucket: 'safeguard-ai-123.firebasestorage.app',
    measurementId: 'G-C1L2TS7PDT',
  );
}
